// =========================================================================
// MÓDULO DE CONFIGURACIÓN MULTIMEDIA FALLBACKS
// =========================================================================
export const CONFIG_MULTIMEDIA = {
  fallbacks: {
    imagen:
      "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400",
    video:
      "https://assets.mixkit.co/videos/preview/mixkit-smart-home-interface-screens-42352-large.mp4",
  },
  ajustes: {
    lazyLoading: true,
    videoMuted: true,
    videoLoop: true,
    videoAutoplay: true,
  },
};

// =========================================================================
// SECCIÓN EXCLUSIVA PARA AGREGAR / EDITAR PRODUCTOS (CATÁLOGO)
// =========================================================================
export const INVENTARIO_LOCAL = [
  {
    id: "prod-001",
    nombre: "SOPORTE PARA CUBIERTOS DE PARED",
    categoria: "Cocina",
    precio: 3.9,
    imagen: "img/cocina/soporte_para_cubiertos_de_pared.png",
    video: "",
  },
  {
    id: "prod-002",
    nombre: "CEPILLO ELECTRICO DE LIMPIEZA BLANCO",
    categoria: "Limpieza",
    precio: 16.9,
    imagen: "img/limpieza/cepillo_electrico_de_limpieza_blanco.png",
    video: "",
  },
  {
    id: "prod-003",
    nombre: "CEPILLO ELECTRICO DE LIMPIEZA GRIS OSCURO",
    categoria: "Limpieza",
    precio: 19.5,
    imagen: "img/limpieza/cepillo_electrico_de_limpieza_gris_oscuro.png",
    video: "",
  },
  {
    id: "prod-004",
    nombre: "DISPENSADOR DE ACEITE DOBLE FUNSION AMARILLO",
    categoria: "Cocina",
    precio: 11.7,
    imagen: "img/cocina/dispensador_de_aceite_doble_funsion_amarillo.png",
    video: "",
  },
  {
    id: "prod-005",
    nombre: "DISPENSADOR DE ACEITE DOBLE FUNSION BLANCO",
    categoria: "Cocina",
    precio: 13.0,
    imagen: "img/cocina/dispensador_de_aceite_doble_funsion_blanco.png",
    video: "",
  },
  {
    id: "prod-006",
    nombre: "CABEZAL DE DUCHA DE MANO",
    categoria: "Baño",
    precio: 9.1,
    imagen: "img/bano/cabezal_de_ducha_de_mano.png",
    video: "",
  },
  {
    id: "prod-007",
    nombre: "REPELENTE ULTRA SONICO (PAQ. 4)",
    categoria: "Hogar",
    precio: 5.2,
    imagen: "img/hogar/repelente_ultra_sonico_paq._4.png",
    video: "",
  },
  {
    id: "prod-008",
    nombre: "PROTECTOR PARA MICROONDA",
    categoria: "Cocina",
    precio: 23.4,
    imagen: "img/cocina/protector_para_microonda.png",
    video: "",
  },
  {
    id: "prod-009",
    nombre: "EXTENSOR DE USB",
    categoria: "Accesorios",
    precio: 7.8,
    imagen: "img/accesorios/extensor_de_usb.png",
    video: "",
  },
  {
    id: "prod-010",
    nombre: "LUZ  LED CON SENSOR DE MOVIMIENTOO TRES COLORES NEGRA (50CM)",
    categoria: "Luces LED",
    precio: 18.2,
    imagen:
      "img/iluminacion/luz_led_con_sensor_de_movimiento_tres_colores_negra_50cm.png",
    video: "",
  },
  {
    id: "prod-011",
    nombre: "LUZ LED RECARGABLE CON SENSOR (30)",
    categoria: "Luces LED",
    precio: 9.1,
    imagen: "img/iluminacion/luz_led_recargable_con_sensor_30.png",
    video: "",
  },
  {
    id: "prod-012",
    nombre: "LUZ LED RECARGABLE CON SENSOR (50)",
    categoria: "Luces LED",
    precio: 10.4,
    imagen: "img/iluminacion/luz_led_recargable_con_sensor_50.png",
    video: "",
  },
  {
    id: "prod-013",
    nombre: "LUZ  LED CON SENSOR DE MOVIMIENTO TRES COLORES BLANCA (40CM)",
    categoria: "Luces LED",
    precio: 16.9,
    imagen:
      "img/iluminacion/luz_led_con_sensor_de_movimient_tres_colores_blanca_40cm.png",
    video: "",
  },
  {
    id: "prod-014",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES NEGROS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_negros.png",
    video: "",
  },
  {
    id: "prod-015",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES BLANCO CON NEGROS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen:
      "img/accesorios/soporte_de_telefonos_flexibles_blanco_con_negros.png",
    video: "",
  },
  {
    id: "prod-016",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES AMARILLOS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_amarillos.png",
    video: "",
  },
  {
    id: "prod-017",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES ROJOS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_rojos.png",
    video: "",
  },
  {
    id: "prod-018",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES AZUL CLARO",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_azul_claro.png",
    video: "",
  },
  {
    id: "prod-019",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES MORADOS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_morados.png",
    video: "",
  },
  {
    id: "prod-020",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES ROSADOS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_rosados.png",
    video: "",
  },
  {
    id: "prod-021",
    nombre: "SOPORTE DE TELEFONOS FLEXIBLES AZUL OSCUROS",
    categoria: "Accesorios",
    precio: 13.0,
    imagen: "img/accesorios/soporte_de_telefonos_flexibles_azul_oscuros.png",
    video: "",
  },
  {
    id: "prod-022",
    nombre: "ORGANIZADOR DE HUEVOS BLANCO",
    categoria: "Cocina",
    precio: 13.0,
    imagen: "img/cocina/organizador_de_huevos_blanco.png",
    video: "",
  },
  {
    id: "prod-023",
    nombre: "LUCES TIPO CORTINA AZUL (3*3)",
    categoria: "Luces LED",
    precio: 14.3,
    imagen: "img/iluminacion/luces_tipo_cortina_azul_3x3.png",
    video: "",
  },
  {
    id: "prod-024",
    nombre: "LUCES TIPO CORTINA MULTICOLOR (3*3)",
    categoria: "Luces LED",
    precio: 14.3,
    imagen: "img/iluminacion/luces_tipo_cortina_multicolor_3x3.png",
    video: "",
  },
];
